FROM metabohub/mama-core:1.2.0

# set author
LABEL maintainer="nils.paulhe@inrae.fr"

# [php] init composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&\
    php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&\
    php composer-setup.php                    &&\
    php -r "unlink('composer-setup.php');"    &&\
    mv composer.phar /usr/local/bin/composer

# add database stuff - tmp test to remove
RUN apt-get update                     &&\
    apt-get install -y mysql-server

WORKDIR /var/www/html/

# [php] copy composer config. files
COPY ./composer.* /var/www/html/

RUN composer update

# [apache2] copy apache2 config.
COPY ./docker-conf/apache2.conf /etc/apache2/apache2.conf
COPY ./docker-conf/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# [php] copy MAMA-REST directoy
COPY . /var/www/html/

# [MAMA] init cron jobs
#COPY docker-conf/crontab /etc/cron.d/mail-cron
#RUN chmod 0644 /etc/cron.d/mail-cron && touch /var/log/cron.log
#RUN crontab /etc/cron.d/mail-cron
#RUN cron

# [other] share volume
RUN chown -R www-data:www-data /var/www/html/
# VOLUME /mnt/mama_uploaded_files:/var/www/html/uploaded_files 

# init live tests databases
RUN usermod -d /var/lib/mysql/ mysql                                                   &&\
    service mysql start                                                                &&\
    mysql --execute=" CREATE DATABASE mama_db CHARACTER SET UTF8;                    " &&\
    mysql --execute=" CREATE USER mama_user@localhost IDENTIFIED BY 'mama_password'; " &&\
    mysql --execute=" GRANT ALL PRIVILEGES ON mama_db.* TO mama_user@localhost;      " &&\
    mysql --execute=" FLUSH PRIVILEGES;                                              " &&\
    cd /var/www/html/                                                                  &&\
    php vendor/bin/doctrine orm:schema-tool:create                                     &&\
    mysql --execute=" USE mama_db;                                                       \
        INSERT INTO users                                                                \
        (email, login, password, user_status, user_right,  email_reception, email_alert_new_user, email_alert_new_project, email_alert_new_event_followed_project, email_alert_new_message, created, last_activity, deleted) \
        VALUES ('nils.paulhe@gmail.com', 'nils.paulhe@gmail.com', 'm*****', 10, 520, 0, 0, 0, 0, 0, curdate(), curdate(), 0);         \
        UPDATE users SET password = '\$2y\$12\$d2VmbHdlZnBtd2VwbXdlZesaBIqV1ghB1p2YPl7ecig3qK3cERppm' WHERE id = 1;               " &&\
    mysql --execute=" USE mama_db; INSERT INTO thematic_words (word, created, deleted) VALUES ('tw1', curdate(), 0);              " &&\
    mysql --execute=" USE mama_db; INSERT INTO sub_thematic_words (word, created, deleted) VALUES ('stw1', curdate(), 0);         " &&\
    mysql --execute=" USE mama_db; INSERT INTO metabohub_platform (platform_name, created, deleted) VALUES ('pf1', curdate(), 0); " &&\
    mysql --execute=" CREATE DATABASE mama_test CHARACTER SET UTF8;                                                               " &&\
    mysql --execute=" CREATE USER mama_test_user@localhost IDENTIFIED BY 'XSaMyduyvpmLenNn';                                      " &&\
    mysql --execute=" GRANT ALL PRIVILEGES ON mama_test.* TO mama_test_user@localhost;                                            " &&\
    mysql --execute=" FLUSH PRIVILEGES;                                                                                           " &&\
    cd /var/www/html/tests                                                                                                          &&\
    php ../vendor/bin/doctrine orm:schema-tool:create

# create entrypoint script    
RUN echo "service apache2 start && service mysql start && tail -f /var/log/apache2/*.log" >> /startup-tests.sh &&\
    chmod +x /startup-tests.sh
    
# exec entrypoint
CMD ["/bin/bash", "-c", "/startup-tests.sh"]

# [END]
