FROM metabohub/mama-core:1.2.0

# set author
LABEL maintainer="nils.paulhe@inrae.fr"

# [php] init composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&\
    php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&\
    php composer-setup.php                    &&\
    php -r "unlink('composer-setup.php');"    &&\
    mv composer.phar /usr/local/bin/composer

# add database stuff - tmp test to remove
RUN apt-get update                     &&\
    apt-get install -y mysql-server

WORKDIR /var/www/html/

# [php] copy composer config. files
COPY ./composer.* /var/www/html/

RUN composer update

# [apache2] copy apache2 config.
COPY ./docker-conf/apache2.conf /etc/apache2/apache2.conf
COPY ./docker-conf/000-default.conf /etc/apache2/sites-enabled/000-default.conf

# [php] copy MAMA-REST directoy
COPY . /var/www/html/

# [MAMA] init cron jobs
#COPY docker-conf/crontab /etc/cron.d/mail-cron
#RUN chmod 0644 /etc/cron.d/mail-cron && touch /var/log/cron.log
#RUN crontab /etc/cron.d/mail-cron
#RUN cron

# [other] share volume
RUN chown -R www-data:www-data /var/www/html/
# VOLUME /mnt/mama_uploaded_files:/var/www/html/uploaded_files 

# init live tests databases
RUN echo "[info] starting mysql service..."                   &&\
    usermod -d /var/lib/mysql/ mysql                          &&\
    service mysql start                                       &&\
    echo "[info] create tests databases..."                   &&\
    cd /var/www/html/                                         &&\
    mysql < tests/create-tests-databases.sql                  &&\
    echo "[info] init 'live test' database..."                &&\
    php vendor/bin/doctrine orm:schema-tool:create            &&\
    echo "[info] add basic content into test databases..."    &&\
    mysql < tests/init-tests-databases.sql                    &&\
    echo "[info] init unit tests database..."                 &&\
    cd /var/www/html/tests                                    &&\
    php ../vendor/bin/doctrine orm:schema-tool:create

# create entrypoint script    
RUN echo "service apache2 start &&\
        service memcached start &&\
        service mysql start     &&\
        tail -f /var/log/apache2/*.log" >> /startup-tests.sh &&\
    chmod +x /startup-tests.sh
    
# exec entrypoint
CMD ["/bin/bash", "-c", "/startup-tests.sh"]

# [END]
