<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */
abstract class AbstractMAMAobject {
	
	// ////////////////////////////////////////////////////////////////////////
	// ATTRIBUTES
	
	/**
	 * @Id @GeneratedValue @Column(type="bigint")
	 * auto-increment
	 *
	 * @var Long
	 * @access protected
	 */
	protected $id;
	
	/**
	 * @Column(type="datetime")
	 *
	 * @var Date
	 * @access protected
	 */
	protected $created;
	
	/**
	 * @Column(type="datetime", nullable=true)
	 *
	 * @var Date
	 * @access protected
	 */
	protected $updated;
	
	/**
	 * @Column(type="boolean")
	 *
	 * @var boolean
	 * @access protected
	 */
	protected $deleted = false;
	
	// ////////////////////////////////////////////////////////////////////////
	// CONSTRUCTORS
	/**
	 */
	public function __construct() {
		$this->created = new \DateTime ( "now" );
		$this->deleted = false;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// GETTERS
	
	/**
	 *
	 * @return Long
	 */
	public function getId() {
		return $this->id;
	}
	
	/**
	 *
	 * @return Date
	 */
	public function getCreated() {
		return $this->created;
	}
	
	/**
	 *
	 * @return Date
	 */
	public function getUpdated() {
		return $this->updated;
	}
	
	/**
	 *
	 * @return boolean
	 */
	public function isDeleted() {
		return $this->deleted;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// SETTERS
	
	/**
	 * update date in database
	 */
	public function setUpdated() {
		$this->updated = new \DateTime ( "now" );
	}
	
	/**
	 */
	public function delete() {
		$this->deleted = true;
	}
}
?>