<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Event
 * @Entity @Table(name="admin_events")
 */
require_once ('Event.class.php');
class AdminEvent extends Event {
	// ////////////////////////////////////////////////////////////////////////
	// STATICS
	
	// ////////////////////////////////////////////////////////////////////////
	// ATTRIBUTES
	/**
	 * @Column(type="string", nullable=false , name="old_name")
	 *
	 * @var String
	 * @access private
	 */
	private $oldName;
	
	/**
	 * @Column(type="string", nullable=true, name="new_name" )
	 *
	 * @var String
	 * @access private
	 */
	private $newName;
	
	// ////////////////////////////////////////////////////////////////////////
	// CONSTRUCTORS
	public function __construct($user, $type, $oldName, $newName) {
		parent::__construct ( $user, $type );
		$this->oldName = $oldName;
		$this->newName = $newName;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// GETTERS / SETTERS
	public function getOldName() {
		return $this->oldName;
	}
	public function setOldName($oldName) {
		$this->oldName = $oldName;
	}
	public function getNewName() {
		return $this->newName;
	}
	public function setNewName($newName) {
		$this->newName = $newName;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// OTHER
	public function prune() {
		parent::prune ();
		$this->id = intval ( $this->getId () );
	}
	
	/**
	 */
	public function getJsonData() {
		$this->prune ();
		$var = get_object_vars ( $this );
		$var ['type'] = $var ['eventType'];
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["deleted"] );
		unset ( $var ["eventType"] );
		foreach ( $var as &$value ) {
			if (is_object ( $value ) && method_exists ( $value, 'getJsonData' )) {
				$value = $value->getJsonData ();
			}
		}
		return $var;
	}
	
	/**
	 */
	public function getArrayData() {
		$this->prune ();
		$ret = Array ();
		$var ['type'] = $var ['eventType'];
		$var = get_object_vars ( $this );
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["deleted"] );
		unset ( $var ["eventType"] );
		foreach ( $var as $key => $val ) {
			// if (is_object ( $val ) && method_exists ( $val, 'getArrayData' )) {
			// $val = $val->getArrayData ();
			// }
			$ret [$key] = object2array ( $val );
		}
		return $ret;
	}
}
?>