<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        AbstractMAMAobject
 * 
 *  @Entity @Table(name="metabohub_platform")
 */
require_once ('AbstractMAMAobject.class.php');
class MTHplatform extends AbstractMAMAobject {
	
	// ////////////////////////////////////////////////////////////////////////
	// STATICS
	
	// ////////////////////////////////////////////////////////////////////////
	// ATTRIBUTES
	
	/**
	 * @Column(type="string", unique=true, nullable=false, name="platform_name" )
	 *
	 * @var String
	 * @access private
	 */
	private $name;
	
	/**
	 * @OneToMany(targetEntity="User", mappedBy="metabohub_platform")
	 *
	 * @var User
	 * @access private
	 */
	private $users;

	// ////////////////////////////////////////////////////////////////////////
	// CONSTRUCTORS
	
	/**
	 *
	 * @param String $name        	
	 */
	public function __construct($name) {
		parent::__construct ();
		$this->name = $name;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// GETTERS / SETTERS
	
	/**
	 *
	 * @return String
	 */
	public function getName() {
		return $this->name;
	}
	
	/**
	 *
	 * @param String $name        	
	 */
	public function setName($name) {
		$this->name = $name;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// OTHER
	/**
	 */
	public function prune() {
		$this->id = intval ( $this->getId () );
		$this->users = [];
	}
	
	/**
	 */
	public function getJsonData() {
		$this->prune ();
		$var = get_object_vars ( $this );
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["users"] );
		foreach ( $var as &$value ) {
			if (is_object ( $value ) && method_exists ( $value, 'getJsonData' )) {
				$value = $value->getJsonData ();
			}
		}
		return $var;
	}
	
	/**
	 */
	public function getArrayData() {
		$this->prune ();
		$ret = Array ();
		$var = get_object_vars ( $this );
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["users"] );
		foreach ( $var as $key => $val ) {
			// if (is_object ( $val ) && method_exists ( $val, 'getArrayData' )) {
			// $val = $val->getArrayData ();
			// }
			$ret [$key] = object2array ( $val );
		}
		return $ret;
	}

	public function getUsers() {
		return $this->users;
	}
	 
	public function setUsers($users) {
		$this->users = $users;
	}
}
?>