<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Event
 * @Entity @Table(name="projects_events")
 * 
 */
require_once ('Event.class.php');
class ProjectEvent extends Event {
	
	// ////////////////////////////////////////////////////////////////////////
	// STATICS
	
	// ////////////////////////////////////////////////////////////////////////
	// ATTRIBUTES
	/**
	 * @ManyToOne(targetEntity="Project", inversedBy="events")
	 * @JoinColumn(name="project_id", referencedColumnName="id", nullable=false)
	 *
	 * @var Project
	 * @access private
	 */
	private $project;
	
	// ////////////////////////////////////////////////////////////////////////
	// CONSTRUCTORS
	public function __construct($user, $type, $project) {
		parent::__construct ( $user, $type );
		$this->project = $project;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// GETTERS / SETTERS
	public function getProject() {
		return $this->project;
	}
	public function setProject($project) {
		$this->project = $project;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// OTHER
	public function prune() {
		parent::prune ();
		$this->id = intval ( $this->getId () );
		$projectS = [ 
				"id" => intval ( $this->project->getId () ),
				"title" => $this->project->getTitle () 
		];
		$this->project = $projectS;
	}
	
	/**
	 */
	public function getJsonData() {
		$this->prune ();
		$var = get_object_vars ( $this );
		$var ['type'] = $var ['eventType'];
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["deleted"] );
		unset ( $var ["eventType"] );
		foreach ( $var as &$value ) {
			if (is_object ( $value ) && method_exists ( $value, 'getJsonData' )) {
				$value = $value->getJsonData ();
			}
		}
		return $var;
	}
	
	/**
	 */
	public function getArrayData() {
		$this->prune ();
		$ret = Array ();
		$var = get_object_vars ( $this );
		$var ['type'] = $var ['eventType'];
		$var = get_object_vars ( $this );
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["deleted"] );
		unset ( $var ["eventType"] );
		foreach ( $var as $key => $val ) {
			// if (is_object ( $val ) && method_exists ( $val, 'getArrayData' )) {
			// $val = $val->getArrayData ();
			// }
			$ret [$key] = object2array ( $val );
		}
		return $ret;
	}
}
?>