<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * 
 * @Entity @Table(name="tokens")
 */
class Token {
	// ////////////////////////////////////////////////////////////////////////
	// STATICS
	public static $TOKEN_LENGTH = 42;
	
	// ////////////////////////////////////////////////////////////////////////
	// ATTRIBUTES
	/**
	 * @Id @GeneratedValue @Column(type="bigint")
	 * auto-increment
	 *
	 * @var Long
	 * @access private
	 */
	private $id;
	
	/**
	 * @Column(type="string", unique=true, nullable=false)
	 *
	 * @var String
	 * @access private
	 */
	private $value;
	
	/**
	 * @Column(type="datetime", nullable=false)
	 *
	 * @var Date
	 * @access private
	 */
	private $validity;
	
	/**
	 * @ManyToOne(targetEntity="User", inversedBy="token")
	 *
	 * @var User
	 * @access private
	 */
	private $user;
	
	// ////////////////////////////////////////////////////////////////////////
	// CONSTRUCTORS
	public function __construct($user) {
		$this->user = $user;
		$this->value = md5 ( uniqid ( rand (), true ) );
		$date = new \DateTime ( "now" );
		$date->add ( new \DateInterval ( 'P10D' ) );
		$this->validity = $date;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// GETTERS
	
	/**
	 *
	 * @return String
	 */
	public function getValue() {
		return $this->value;
	}
	
	/**
	 *
	 * @return Date
	 */
	public function getValidity() {
		return $this->validity;
	}
	
	/**
	 *
	 * @return User
	 */
	public function getUser() {
		return $this->user;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// OTHER
	/**
	 *
	 * @access public
	 * @return boolean
	 */
	public final function isValid() {
	}
	
	/**
	 *
	 * @access public
	 * @return boolean
	 */
	public final function isUserAdmin() {
	}
	
	/**
	 *
	 * @access public
	 * @return boolean
	 */
	public final function isUserProjectManager() {
	}
	
	/**
	 *
	 * @access public
	 * @param long $projectID        	
	 * @return boolean
	 */
	public final function isInvolvedInProject(long $projectID) {
	}
	
	/**
	 */
	public function prune() {
		$this->id = null;
		// $this->user = null;
	}
	
	/**
	 */
	public function getJsonData() {
		$this->prune ();
		$var = get_object_vars ( $this );
		// unset ( $var ["user"] );
		unset ( $var ["id"] );
		foreach ( $var as &$value ) {
			if (is_object ( $value ) && method_exists ( $value, 'getJsonData' )) {
				$value = $value->getJsonData ();
			}
		}
		return $var;
	}
	
	/**
	 */
	public function getArrayData() {
		$this->prune ();
		$ret = Array ();
		$var = get_object_vars ( $this );
		// unset ( $var ["user"] );
		unset ( $var ["id"] );
		foreach ( $var as $key => $val ) {
			// if (is_object ( $val ) && method_exists ( $val, 'getArrayData' )) {
			// $val = $val->getArrayData ();
			// }
			$ret [$key] = object2array ( $val );
		}
		return $ret;
	}
	
	/**
	 */
	public function renewValidity() {
		$date = new \DateTime ( "now" );
		$date->add ( new \DateInterval ( 'P10D' ) );
		$this->validity = $date;
	}
}
?>