<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Event
 * @Entity @Table(name="users_events")
 */
require_once ('Event.class.php');
class UserEvent extends Event {
	// ////////////////////////////////////////////////////////////////////////
	// STATICS
	
	// ////////////////////////////////////////////////////////////////////////
	// ATTRIBUTES
	/**
	 * @ManyToOne(targetEntity="User", inversedBy="events")
	 * @JoinColumn(name="event_user_id", referencedColumnName="id", nullable=false)
	 *
	 * @var User
	 * @access private
	 */
	private $eventUser;
	
	// ////////////////////////////////////////////////////////////////////////
	// CONSTRUCTORS
	public function __construct($user, $type, $eventUser) {
		parent::__construct ( $user, $type );
		$this->eventUser = $eventUser;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// GETTERS / SETTERS
	public function getEventUser() {
		return $this->eventUser;
	}
	public function setEventUser($eventUser) {
		$this->eventUser = $eventUser;
	}
	
	// ////////////////////////////////////////////////////////////////////////
	// OTHER
	
	public function prune() {
		parent::prune();
		$this->id = intval ( $this->getId () );
		$eventUserS = [
				"id" => intval ( $this->eventUser->getId () ),
				"fullName" => $this->eventUser->getFirstName () . " " . $this->eventUser->getLastName ()
		];
		$this->eventUser = $eventUserS;
	}
	
	/**
	 */
	public function getJsonData() {
		$this->prune ();
		$var = get_object_vars ( $this );
		$var ['type'] = $var['eventType'];
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["deleted"] );
		unset ( $var ["eventType"] );
		foreach ( $var as &$value ) {
			if (is_object ( $value ) && method_exists ( $value, 'getJsonData' )) {
				$value = $value->getJsonData ();
			}
		}
		return $var;
	}
	
	/**
	 */
	public function getArrayData() {
		$this->prune ();
		$ret = Array ();
		$var ['type'] = $var['eventType'];
		$var = get_object_vars ( $this );
		unset ( $var ["__initializer__"] );
		unset ( $var ["__cloner__"] );
		unset ( $var ["__isInitialized__"] );
		unset ( $var ["deleted"] );
		unset ( $var ["eventType"] );
		foreach ( $var as $key => $val ) {
			// if (is_object ( $val ) && method_exists ( $val, 'getArrayData' )) {
			// $val = $val->getArrayData ();
			// }
			$ret [$key] = object2array ( $val );
		}
		return $ret;
	}
	
}
?>